
;output_buffering = 4096
;default_socket_timeout = 60
;pdo_mysql.cache_size = 2000
;mysql.allow_persistent = On

session.auto_start = off

date.timezone="Europe/Paris"

opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 100000
opcache.max_wasted_percentage = 15
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

sendmail_path = '/usr/bin/msmtp -t'
